language: node_js
node_js:
  - '9'
services:
  - docker
sudo: required

## test
script:
  - make image && make test

## deploy
deploy:
  provider: script
  script: docker login -u $DOCKER_USER -p $DOCKER_PASS && make release
  on:
    branch: master

env:
  global:
  - secure: SPMcv5BLvA7YB4HBdXaytbUQD+gmS+Y33CXC0IZs0ZbTV6EOjD9QRAgv7wwq/IDFuMkPqYUXTPV6BVgspenSfyREsvTi7Ljk31KzfQvUtOk95Ggm3DjaaiHm04dIFBINyOCF+hAgzDDPV+O/4K30zIJtz1KYFm4/ej5wmFrgitBPFt4sXrIrc0QttH1Qb5jBHxU3cPbz/xCH+qgd9W98f/zvAM8yEFVXkJKCMpYpGNqb8HR/tA1zXt2zw9NonY+empp3nDSxoiE3LVjFu23zBuvjXOwVcfQCLFcZzZ571SXc4ADce0NXNdr1IrbR+7IsQCuOJvA1yxBsyYc8C4Qiy6Zw+y1RKomNYOxaZ+QbW2OJhcI/VyafPrUjC/Hq0IHoM8PN8eHwn62SBZ1SsbghZRQUqMWN5enTdU21tHDZF250M1wd7s415CmcgCbdW7TqwgbKiRlpSJbRqEIeRei8Q0bOJiWBIYBCWmQi+EXt6tM+givlAyPSo6lKn/yMaF1YjvI3XQJHZPxSPCv6xpK28nlbXFMm7ep120CSAY89M9HDraO87fhaVT6q7rreTGz0Ol0Sm+oHzbr7SfWDU/8J6xd559Z5flbIt/V0atLtoXsb+PRFakCXJlqYR7j6BuwhlflXOpIECD8/Yf1BLX6LJId43cxSo6Hup+TdlvhLD6M=
  - secure: TnvxcYvCMTUtOyoUaG4me4XpehCl1o3Ol3xRqCfXPAbk1ykGQ1LkrAa3pZiAV3tH4QFKHkMCLMhObD8tCZXrEtHZP+C3O6Ii79yn+1BHwLgcohc/0E+LIpmUSsYTwrqscQjnpIJpE6AdJhcP/hCG96YJzu9YqYY2Hbl23GKVMAWaNqK3yl1lpOrhEqA3WblVqeeeQhslDd56KTbhxICuoafL05qBQIzQ0dJHRC9JMoZ1WkCAwaH1YCWJQYvHmAIbAtOUn2hSsCkT9H7g24WInm0RpG3IQdT0JWcolvGl8HBsIKxzKrYB0TyktxsDw1AAIoTSV4Zh6Amjz47PIKGPJM/F+Jb2hdVkZmurHrVptDWFwehLIAUHEJ4vzyy7kFJBaY+aOL2Pt6eMt1VLqxi3EbjKrGI/4CFpsnJqH8Ncefy9MU555nBD9HO3E99ihbZddMBEqOSt1bSqdT6WLxz1mrf9QdiG6EZfjF7twwVGFaxCLdS7noMwljApJDccfG1KjjumaoHvF0oy1w3ns8YrCPVvOz+qnmbpvxsyy8qSZaWhwRef0ytfJa2lfVEkoCGqVhxJn+Is+NIUo1G6l2EQhMFNGotpQ0YBx9FUea1X9gqS6RXXSEyEL97r0/oMZb7wyR3DEhdMDlvOPhJI/7MdbhKKAxIYDpXjuiOmLB32fy8=
  - secure: lTaOHQfERwis9JtCzfViRJTN2zFh9gIo9zn+hj5sp45HpeKusy4udwECKqCHWw/jK29UFYiHt2Jy1N3FpOZrN44bgIW2lbU0EVhAyX24HnrSMO2beol5NiY1ZTLU82wxJOXn4Rgw+2CRrCE82aBObpI3kVbkGSxL/XWBUVXnWV5ZaJXUFE/n62OrzzdieJvwjfnhvrKFsQ0tNs3Imp6aRvy1vlSSLpyTGxORqx9/iersNLUKy7WsZp0q7OXo0P9sR5nIXrA2j1Jhi2njl2W8xtYGZcvwKFTAjOlWYiUxVUEN833aNdqjxt3Ucse/WzNWaPIRqUNB1xHFs06MmLurD46edONEfOvQ+IuVBIhR0h1OxrZPAS8j9dx0npO4PbmfxbNRt0vlSY7ez28DcqyLaEBRRyKFuluoHaxKtriIjjh9p9xcXeI5aVxEBubKMIvnurRRuNTHE/cEV2n/A1acypTr/X7SnAuVSC3ouxTBf5VZCwh2gz0ExHh8sssZKu33uPvdMoqQQ88zcmu5obaE3/tRXtNARnyqryCZFBUVPaHM2pR59oYHb5Prc5KpANKqVQq7ae66CiSnwlNfDuwrExhyqffy1PvuOj2YGeIUNCSINmmlDpaG9ZP19B+ctDLGHxtjnjayuoMXBvzMsORF7cF9ewvNf8q1NV7uP6GZg/c=
